<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <div class="sticky" 
                style=" position: fixed;
                        bottom: 1px;
                        right: 0;
                        background: #f5f5f5;
                        border-top: 1px #ccc solid;
                        padding: 0 20px;
                        line-height: 1.42857143;
                        margin: 13px 0 0 0;
                        display: inline-block;
                        width: 100%;
                        z-index: 99;">
                <button type="submit"
                    title="<?= $block->escapeHtml(__('Add to Bulk Cart')) ?>"
                    class="action tocart primary bulkadd"
                    style="float:right;"
                    formaction="/product/bulkadd">
                    <span><?= /* @escapeNotVerified */ __('Add to Bulk Cart') ?></span>
                </button>
            </div>
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            $itemId = $_product->getId();
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                        <?= $block->getProductDetailsHtml($_product) ?>
                        
                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form id="bulkaddtocart-<?php echo $block->escapeHtml($itemId) ?>" name="addcart" data-mage-init='{"validation":{}}' data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product[]" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <div class="field qty">
												<label class="label" for="qty"><span>Qty</span></label>
												<div class="control">
													<input id="<?php echo $block->escapeHtml($itemId) ?>" type="number" name="qty" value="0" title="Qty" class="input-text qty" data-validate="{'required-number':true,'validate-item-quantity':{'minAllowed':1}}">
												</div>
											</div>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                    class="action tocart primary"
                                                    id="btn<?php echo $block->escapeHtml($itemId) ?>">
                                                <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                       class="action more"><?= /* @escapeNotVerified */ __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
<script>
    require(['jquery'], 
    function($){

        $("button.bulkadd").click(function(){
            $("input.input-text.qty").each( function(){ 
                if($(this).val() >= 1 && $(this).val() != 0){
                    var formid = "#bulkaddtocart-" + $(this).attr('id');
                    $(formid).submit();
                }
            });
        });

        $("input.input-text.qty").each( function(){
            if($(this).val() < 1 && $(this).val() == 0){
                $(this).parents('.field').next('button[type="submit"]').attr('disable', true);
                $(this).parents('.field').next('button[type="submit"]').addClass("disable disabled");
            }
            else{
                $(this).parents('.field').next('button[type="submit"]').attr('disable', false);
                $(this).parents('.field').next('button[type="submit"]').removeClass("disable disabled");
            }
        });

        $("input.input-text.qty").keyup( function(){
            $(this).each( function(){
                var swatch = 'div.swatch-opt-' + $(this).val();
                $(this).parents('div.product-item-inner').prev('script').prev(swatch).find('div.swatch-attribute').each(function(){
                    var attr = $(this).parents('div.product-item-inner').prev('script').prev(swatch).find('div.swatch-attribute').attr('option-selected');    
                    if (typeof attr == typeof undefined) {
                        alert(attr);
                        $(this).parents('.field').next('button[type="submit"]').attr('disable', true);
                        $(this).parents('.field').next('button[type="submit"]').addClass("disable disabled");
                    }else{
                        if($(this).val() < 1 && $(this).val() == 0){
                            $(this).parents('.field').next('button[type="submit"]').attr('disable', true);
                            $(this).parents('.field').next('button[type="submit"]').addClass("disable disabled");
                        }
                        else{
                            $(this).parents('.field').next('button[type="submit"]').attr('disable', false);
                            $(this).parents('.field').next('button[type="submit"]').removeClass("disable disabled");
                        }
                    }
                });
            });
        });
    });
</script>